// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTxuI_o_xn3lxu1BkYW8n2Wn97N_RGMY',
    appId: '1:100628899608:web:b6190118ca935460e9206d',
    messagingSenderId: '100628899608',
    projectId: 'yabatechsearch',
    authDomain: 'yabatechsearch.firebaseapp.com',
    storageBucket: 'yabatechsearch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkWRhjTF5h-IesPdav6uHBwLaHIi5wxA',
    appId: '1:100628899608:android:8a816d11597495c5e9206d',
    messagingSenderId: '100628899608',
    projectId: 'yabatechsearch',
    storageBucket: 'yabatechsearch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBTcuknZzFX6dOqk8OpFJLz19vSv0faPk',
    appId: '1:100628899608:ios:67d40238d224f929e9206d',
    messagingSenderId: '100628899608',
    projectId: 'yabatechsearch',
    storageBucket: 'yabatechsearch.appspot.com',
    iosClientId: '100628899608-ve8bqqvfusde9el5cj4durj7786gm8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSearchEngine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBTcuknZzFX6dOqk8OpFJLz19vSv0faPk',
    appId: '1:100628899608:ios:67d40238d224f929e9206d',
    messagingSenderId: '100628899608',
    projectId: 'yabatechsearch',
    storageBucket: 'yabatechsearch.appspot.com',
    iosClientId: '100628899608-ve8bqqvfusde9el5cj4durj7786gm8gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSearchEngine',
  );
}
